### ISSUE TITLE
Double speed upon unpausing

### ISSUE THREAD

**Issue by jazzyclimber** [jazzyclimber/podomoro-timer#2]
The work timer seems to double in speed if it is restarted after being paused. Ergo - each time you click play it speeds up? Difficult to tell what is actually going on. 

I think it is building a new timer each time play is pushed causing their effects to stack on top of one another each second. ie. if play is pushed 3 times then every second that passes 3 seconds get taken off of the timer.

**Comment by jazzyclimber** [comment]
** @NiccoMaganeli Nice work on getting this issue resolved. I think we can merge this with working_space - assuming you are OK with the edits. 

Changes made:
  - set interval = null
    - I think this is best practice to do this instead of undefined for debugging purposes. typeof (undefined) // undefined whereas typeof (null) // object. This makes it easier to tell if the browser is throwing up undefined or if a variable simply wasnt given a value. Does that make sense?
  - Deleted all instances of isPaused
  - Removed first nesting if statement of countDown()
  - clearInterval(interval) on setPause()

**Comment by NiccoMaganeli** [comment]
Closing it since we've already solved it.
